#ifndef V
#define V(key, value)
#endif
V(enabled, "enabled(need restart)")

V(lang_name, "english")

V(heart_config, "HEART Config")
V(heart_devices, "HEART Devices")
V(heart_senders, "HEART Senders")
V(heart_osc_senders, "HEART OSC Senders")
V(hyperate, "HypeRate")
V(pulsoid, "Pulsoid")

V(hyperate_reset, "RESET")
V(hyperate_save_and_connect, "SAVE AND CONNECT")
V(hyperate_input_hint, "https://app.hyperate.io/<color=\"green\">xxx</color><-input this")
V(no_message_from_server, "")

V(hyperate_con_start, "Connect start")
V(hyperate_network_error, "Network error: ")
V(hyperate_retry, "retry")
V(hyperate_connected, "Connected.")
V(hyperate_no_id, "No hyperate ID")
V(hyperate_refused, "Refused by server")
V(hyperate_you_have_message, "you have message")

V(pulsoid_no_token, "No token")

V(unsupported_feature_udpatre_mod, "UI unsupported, maybe update your mod")

V(heart_osc_port, "OSC Port: %d")

V(scan_start, "Start Scan")
V(scan_stop, "Stop Scan")
V(turn_location_on, "Need Accuracy Location Perm")

V(scaning, "Scaning")
V(auto_scaning, "Auto scaning")
V(no_scan, "Scan stopped")

V(ble_none_selected, ">> None")
V(ble_none_not_selected, "None")


V(ble_permission_unknown, "Permission manifest check error")
V(ble_permission_needed, "Bluetooth permission missing for game")
V(ble_permission_paired_only, "Paired only，need more permission")

V(pairing, "Pairing.. click to stop.")
V(not_pairing, "Not pairing.. click to start.")
V(hiding_mac_addr, "hiding mac address, click to show.")
V(showing_mac_addr, "showing mac address, click to hide")
V(unknown_left_quote, "Unknown(")
V(server_skip, "skip ")
V(unknown_addr_server_fmt, "%s unknown addr.")
V(heart_rate_lan_protocol_ver, "Heart Rate Lan Protocol Ver ")
V(mod_version, "Mod version " VERSION)
V(for_game, "For Game " GAME_VERSION)
V(no_beatleader, "Beatleader not detected or supported, record is disabled")
V(waiting, "Waiting...")

V(config_adjust_speed, "Config Adjust Speed")

V(text_color, "Text Color")
V(flash_text_color, "Flash Text Color")
V(replay_flash_text_color, "Replay Flash Text Color")
V(flash_duration_when_text_come, "Flash duration when data come")
V(flash_test, "Flash Test")

V(line_space, "Line Space")
V(reset_default_line_space, "Reset Default Line Space")

V(reset_to_default, "Reset to default")

V(data_source, "data source(need restart)")

V(data_source_random, "random")
V(data_source_lan, "(deprecated)local network")
V(data_source_bluetooth, "bluetooth")
V(data_source_osc, "OSC")
V(data_source_hyperate, "HypeRate")
V(data_source_pulsoid, "Pulsoid")

V(enable_record, "Enable Record")
V(record_dev_name, "Save Device Name To Record")

V(age, "Age")

V(select_ui, "Select UI")
V(max_heart, "Max Heartrate")

V(pulsoid_reconnect, "Click to Reconnect")
V(pulsoid_input_hint, "Click Connect to open browser")
V(pulsoid_edit_config_hint, "You can also edit config file to input pulsoid token manually:")
V(pulsoid_connect, "Connect")
V(pulsoid_done, "Done")
V(pulsoid_cancel, "Cancel")
V(pulsoid_token, "Pulsoid Token")
V(pulsoid_clear_token, "Clear and Reset")

V(your_setthings_is_in_another_menu, "Thank you Player! But data-source config is in another menu!")

V(ui_not_avaliable_in_qounter, "Heart UI not avaliable in qounters. Please add HeartRate text source at qounters.")
V(ignore_qounters, "Ignore Qounters++ mod")
V(ignore_qounters_hint, "please enable this if Qounters++ is disabled. If enabled, Qounters++ may not work with this mod.")

V(advance_ui_required, "Hint:Need enable Advanced HUD to see this UI")

V(mdns_enable, "Enable mDNS")
V(mdns_name_no, "mDns n/a")
V(mdns_name_title, "mDns name:")
